service: trapp

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

  environment:
    USER_TABLE: "userdata-${opt:stage, self:provider.stage}"
    EXERCISE_TABLE: "exercisedata-${opt:stage, self:provider.stage}"
    ACTIVITY_TABLE: "activitydata-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"

functions:
  getExercises:
    memorySize: 128
    handler: handler.get
    events:
      - http:
          path: data
          method: get
          cors: true
  getExercisesByType:
    memorySize: 128
    handler: handler.getByType
    events:
      - http:
          path: data/type/{type}
          method: get
          cors: true
  addExercise:
    memorySize: 128
    handler: handler.submit
    events:
      - http:
          path: data
          method: post
          cors: true
  getActivity:
    memorySize: 128
    handler: handler.getActivity
    events:
      - http:
          path: data/activity
          method: get
          cors: true
  getUser:
    memorySize: 128
    handler: handler.getUser
    events:
      - http:
          path: data/user
          method: get
          cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "userID"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "userID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.USER_TABLE}
    ExerciseDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "userID"
            AttributeType: "S"   
          -
            AttributeName: "date"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "userID"
            KeyType: "HASH"
          -
            AttributeName: "date"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.EXERCISE_TABLE}
    ActivityDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "userID"
            AttributeType: "S"   
          -
            AttributeName: "date"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "userID"
            KeyType: "HASH"
          -
            AttributeName: "date"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.ACTIVITY_TABLE}

plugins:
  - serverless-finch

custom:
  client:
    bucketName: aikojentanssi
    distributionFolder: frontend
